import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const tabs=await(await fetch('http://127.0.0.1:9227/json')).json();const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let seq=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.id){const p=pending.get(d.id);if(p){pending.delete(d.id);d.error?p.reject(Error(d.error.message)):p.resolve(d.result);}}else if(d.method==='Runtime.exceptionThrown')errors.push(d.params.exceptionDetails.text);};
const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
async function ev(expression){const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function until(expression){for(let i=0;i<80;i++){if(await ev(expression))return;await new Promise(r=>setTimeout(r,150));}throw Error(expression);}
await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await cdp('Page.navigate',{url:'http://127.0.0.1:8086/'});await until('document.readyState==="complete"&&typeof state!=="undefined"&&state.skills.length>0');
const root=await cdp('DOM.getDocument');const input=await cdp('DOM.querySelector',{nodeId:root.root.nodeId,selector:'#photo'});await cdp('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[process.cwd()+'\\target\\verification\\math-work.jpg']});await until('!!state.image');
assert(await ev('document.querySelector("#drop").hidden'));assert.equal(await ev('document.querySelector("#photo-canvas").parentElement.id'),'photo-stage');
const original=await ev('({w:state.image.width,h:state.image.height})');await ev('document.querySelector("#crop").click()');assert(await ev('document.querySelector(".crop-dialog").open'));
const r=await ev('(()=>{const r=document.querySelector("#photo-canvas").getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}})()');
await cdp('Input.dispatchMouseEvent',{type:'mousePressed',x:r.x+r.w-3,y:r.y+r.h-3,button:'left',clickCount:1});await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',x:r.x+r.w-160,y:r.y+r.h-65,button:'left',buttons:1});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',x:r.x+r.w-160,y:r.y+r.h-65,button:'left',clickCount:1});
assert(await ev('state.selection.w<document.querySelector("#photo-canvas").width'));
await fs.mkdir('target/verification',{recursive:true});async function shot(name){const s=await cdp('Page.captureScreenshot',{format:'png'});await fs.writeFile('target/verification/'+name+'.png',Buffer.from(s.data,'base64'));}
await shot('crop-dialog-desktop');await ev('[...document.querySelectorAll(".crop-dialog button")].find(b=>b.textContent==="应用裁剪").click()');await until('!document.querySelector(".crop-dialog").open');assert(await ev('state.image.width<'+original.w));
await ev('document.querySelector("#reset-photo").click()');await until('state.image.width==='+original.w);await ev('document.querySelector("#crop").click()');await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await until('!document.querySelector(".crop-dialog").open');assert.equal(await ev('state.image.width'),original.w);
await ev('document.querySelector("#photo-editor").scrollIntoView({block:"center"})');await shot('photo-replaces-upload');
await ev('state.diagnosis={id:"ui-test"};renderLessons({lessons:[],message:"本地暂无适配短片"},"ui-test","discriminant-count")');assert(await ev('!!document.querySelector(".online-search button")'));await ev('document.querySelector(".online-search").scrollIntoView({block:"center"})');await shot('online-search-entry');
await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await ev('document.querySelector("#crop").click()');await shot('crop-dialog-mobile');assert(await ev('document.querySelector(".crop-dialog").getBoundingClientRect().width<=innerWidth'));await ev('[...document.querySelectorAll(".crop-dialog button")].find(b=>b.textContent==="取消").click()');
assert.deepEqual(errors,[]);console.log('CROP_AND_ONLINE_UI_OK');ws.close();
