import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const tabs=await(await fetch('http://127.0.0.1:9227/json')).json(),ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let seq=0;const pending=new Map();ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.id){const p=pending.get(d.id);pending.delete(d.id);if(p)d.error?p.reject(Error(d.error.message)):p.resolve(d.result);}};
const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
async function ev(expression){const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await cdp('Page.navigate',{url:'http://127.0.0.1:8086/'});for(let i=0;i<60;i++){if(await ev('document.readyState==="complete"&&typeof state!=="undefined"&&state.skills.length>0'))break;await new Promise(r=>setTimeout(r,200));}
await ev('(async()=>{const h=await api("/history");const d=h.diagnoses.find(d=>d.id==="d6c87e67-6bbe-4662-965a-2fd9fe8a8d89");await loadPhoto(await(await fetch("/api/v2/diagnoses/"+d.id+"/photo")).blob());state.diagnosis=d;renderDiagnosis(d);document.querySelector("input[name=skill][value=quadratic-completing-square]").click();document.querySelector("#diagnosis form button").click();})()');
for(let i=0;i<180;i++){if(await ev('!!document.querySelector(".online-search")||!!document.querySelector("#lessons video")'))break;await new Promise(r=>setTimeout(r,1000));}
if(await ev('!!document.querySelector(".online-search")'))await ev('document.querySelector(".online-search input").value="初中数学 配方法 完全平方公式";document.querySelector(".online-search button").click();document.querySelector("#lessons").scrollIntoView({block:"center"});');
let last='',done=false;for(let i=0;i<720;i++){if(await ev('!!document.querySelector("#lessons video")')){done=true;break;}const message=await ev('document.querySelector(".online-search [role=status]")?.textContent||""');const stage=message.replace(/ · \d+ 秒/g,'');if(stage!==last){console.log('PROGRESS',stage);last=stage;}if(message.includes('本次没有生成')||message.includes('本次没有取得'))throw Error(message);await new Promise(r=>setTimeout(r,1000));}
assert(done,'No independently clipped video was returned');for(let i=0;i<60;i++){if(await ev('document.querySelector("#lessons video").readyState>=1'))break;await new Promise(r=>setTimeout(r,250));}
const result=await ev('({duration:document.querySelector("#lessons video").duration,src:document.querySelector("#lessons video").getAttribute("src"),text:document.querySelector("#lessons").textContent})');assert(result.duration>=5&&result.duration<=361);assert(result.src.startsWith('/api/v2/clips/'));assert(result.text.includes('未经老师人工审核'));
await ev('document.querySelector("#lessons video").muted=true;document.querySelector("#lessons video").play()');await new Promise(r=>setTimeout(r,1000));assert(await ev('document.querySelector("#lessons video").currentTime>0'));await ev('document.querySelector("#lessons video").pause();document.querySelector("#lessons").scrollIntoView({block:"center"})');const screenshot=await cdp('Page.captureScreenshot',{format:'png'});await fs.writeFile('target/verification/online-generated-clip.png',Buffer.from(screenshot.data,'base64'));console.log('ONLINE_PIPELINE_AND_PLAYBACK_OK',JSON.stringify(result));ws.close();
